### ISSUE TITLE
'TransformerTorchEncoder' object has no attribute '_device' when running Lyrics Search

### ISSUE THREAD

**Issue by canetcesc** [jina-ai/examples#100]
Following up on #97, I decided to run the Lyrics Search code on my local machine (no Docker) as that would allow me to copy the toy dataset into the `./data` folder (with this docker image I am unable to log inside using bash, it automatically calls `app.py`).

The problem is when I run `app.py index`. I get the following error:

```
join_all@18945[I]:collected 2/2 parts of IndexRequest
        gateway@18763[E]:callback() may not work properly due to the bad response: encoder-1(TransformerTorchEncoder) throws AttributeError("'TransformerTorchEncoder' object has no attribute '_device'")
        gateway@18763[E]:[pod: "encoder-1"
pod_id: "0ceea959f9"
executor: "TransformerTorchEncoder"
exception: "AttributeError(\"\'TransformerTorchEncoder\' object has no attribute \'_device\'\")"
traceback: "Traceback (most recent call last):\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/peapods/pea.py\", line 275, in msg_callback\n    self.zmqlet.send_message(self._callback(msg))\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/peapods/pea.py\", line 264, in _callback\n    self.pre_hook(msg).handle(msg).post_hook(msg)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/peapods/pea.py\", line 161, in handle\n    self.executor(self.request_type)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/__init__.py\", line 553, in __call__\n    d()\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/drivers/encode.py\", line 31, in __call__\n    embeds = self.exec_fn(contents)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/decorators.py\", line 158, in arg_wrapper\n    return func(self, data, *args, **kwargs)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/decorators.py\", line 58, in arg_wrapper\n    r = func(self, *args, **kwargs)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/encoders/nlp/transformer.py\", line 71, in encode\n    seq_output, *extra_output = self.model(token_ids_batch, attention_mask=mask_ids_batch)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/encoders/nlp/transformer.py\", line 122, in model\n    self._model = self.get_model()\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/encoders/nlp/transformer.py\", line 250, in get_model\n    self.to_device(_model)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/frameworks.py\", line 95, in to_device\n    model.to(self.device)\n  File \"/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/frameworks.py\", line 41, in device\n    if self._device is not None:\nAttributeError: \'TransformerTorchEncoder\' object has no attribute \'_device\'\n"
time {
  seconds: 1594802831
  nanos: 597826000
}
```

(_By the way, I learned the hard way that the number before the seconds is the training example:_
`index [====                ] 📃    832 ⏱️ 148.7s 🐎 5.6/s    104      batch`

_in the case of the toy dataset there are just 1,000 training examples and it takes just a few minutes, so it is definitely impossible to process the entire lyrics dataset on a desktop. It would have helped me **a lot** to get the total number of training examples next to the number eg: `832/167,499` to understand that the code would basically "never end" on a a macbook._ )

Eventually, indexing ends, but I anyway got the same error when running the search:

```
curl --request POST -d '{"top_k": 10, "mode": "search",  "data": ["text:hey, dude"]}' -H 'Content-Type: application/json' 'http://0.0.0.0:65481/api/search'`

"status": {
    "code": "ERROR",
    "description": "tf_encode(TransformerTorchEncoder) throws AttributeError(\"'TransformerTorchEncoder' object has no attribute '_device'\")",
    "details": [
      {
...
```
I installed all the requirements and upgraded to the last version of jina, transformers, torch, etc. What am I doing wrong?

**Comment by JoanFM** [comment]
Hey @canetcesc,
sorry for the inconvenience, but this problem should have been fixed recently in the PR https://github.com/jina-ai/jina/pull/645. 
You may prefer to use the most recent level of master?

**Comment by canetcesc** [comment]
Yeah, that did the trick. Thank you very much!

**Comment by YueLiu-jina** [comment]
Hi @canetcesc,

I meet the same problem a few days ago, but I think it should have been fixed in a PR: https://github.com/jina-ai/jina/pull/645,
maybe the jina package haven't been updated accordingly.

If you would like to fix it manually, could you please open the file at
`/Users/cesc/opt/anaconda3/envs/CescPython37/lib/python3.7/site-packages/jina/executors/frameworks.py`,
detect a line
`if self._device is not None:`
and replace it with
`if getattr(self, '_device', None):`
everything should work then.

**Comment by canetcesc** [comment]
Thanks anyway, Yue Liu!
