### ISSUE TITLE
topk should be change to top_k

### ISSUE THREAD

**Issue by tagizaade** [jina-ai/examples#102]
In the example for south-park semantic search the parameter topk for search task should be replaced with top_k.
https://github.com/jina-ai/examples/blob/b4266a5399fb41a8221acad3f0fcb30e00651b94/southpark-search/app.py#L57

**Comment by nan-wang** [comment]
Thanks for your comment! We'll correct this.

@YueLiu-jina Would you have a look into this?

**Comment by YueLiu-jina** [comment]
@tagizaade You are right. Thank you for your kind reminding!
