### ISSUE TITLE
Issue on Windows 10 . Shows os error 

### ISSUE THREAD

**Issue by rutulgandhi05** [jina-ai/examples#106]
![picturemessage_tsw3vcrz 5gq](https://user-images.githubusercontent.com/46491360/87939391-a0917500-cab5-11ea-98ec-8206aa4999b0.png)

Ran the code code unchanged. Used the same  pods files (.yml files). Shows an error of os .

**Comment by nan-wang** [comment]
@rutulgandhi05  Many thanks for your interests! However, Windows is not supported yet. Please stay tuned.

**Comment by Zenahr** [comment]
@nan-wang Could you guys add this info at the top of the readme? Ran into this myself as well.

**Comment by JoanFM** [comment]
Windows has been clarified here https://docs.jina.ai/master/chapters/install/os/on-wsl.html
