### ISSUE TITLE
[zh/webqa-search] 'jina.executors.indexers.vector.milvusdb.milvusdbhandler' can't be imported

### ISSUE THREAD

**Issue by yiouyou** [jina-ai/examples#110]
Follow the introduction of webqa-search exmaple, everything seems fine, but still get an Error as below:
```
JINA@5762[E]:theses modules or classes can not be imported ['jina.executors.indexers.vector.milvusdb.milvusdbhandler']
```
Any idea what's wrong and how to fix this?

btw, I tried other example, all of them has this problem.

The python version is 3.8.2 with ubuntu 20.04, and jina version is 0.4.0.

**Comment by JoanFM** [comment]
Hey @yiouyou ,

Thanks for raising the issue, it has already been fixed on the master branch. It should not cause any further damage than printing the error message, right?

**Comment by hanxiao** [comment]
**warning: the current master includes breaking changes!** update to master solves the Milvus warning but `webqa-search` won't work anymore.

**Comment by yiouyou** [comment]
@hanxiao If there'are any updates to solve the issue, please let me know, thanks!!

**Comment by JoanFM** [comment]
Hey @yiouyou , this message is not supposed to have any impact; but if you want to get rid of it you can install pymilvus dependency and it should disappear. In later PRs this issue has been solved together with some breaking changes, that is why we do not suggest you to move to the most recent version.
