### ISSUE TITLE
examples/Jina Command-Line Interface url error

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/examples#113]
The invalid url is: https://docs.jina.ai/chapters/cli/main.html , it should be replaced with https://docs.jina.ai/chapters/cli/index.html.

The error of the link has led to a Page Not Found error in all examples, [Documentation Section](https://github.com/jina-ai/examples/tree/master/face-db-search#documentation),  behind text *Jina command line interface arguments explained*.

**Comment by YueLiu-jina** [comment]
Thank you for your reminding!
