### ISSUE TITLE
examples/jina-0.4.1 migration

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/examples#116]
As was discussed, I'll start working on Jina examples migrations for Jina `0.4.1` release following the migration plan [here](https://github.com/jina-ai/jina/issues/702).

This issue is about to set up `0.4.1` migration for all the examples

|  Example  | Migrate-by  |  Peer-tested-by |  Status  | Pull Request |
|---|---|---|---|---|
|   face-db-search |  @bwanglzu  | @YueLiu-jina   |  Merged | #117  |
|  faiss-search | @bwanglzu   |   | Merged | #130   |
| flower-search  | @YueLiu-jina  |  |  Merged |  #119 |
|  helloworld-in-cs | @YueLiu-jina  |   | Merged  | #140  |
|  in-mock-app | @YueLiu-jina  |   |  Merged | #125  |
|  multilingual-search | @bwanglzu  |   | Merged  |  #127  |
| multires-lyrics-search  | @bwanglzu   |   | Merged  | #128   |
|  pokedex-with-bit | @bwanglzu   |  @YueLiu-jina | Merged  | #120  |
|  southpark-search  | @YueLiu-jina   | @bwanglzu   | Merged  | #119  |
| tumblr-gif-search  |  @bwanglzu  |   |  Merged | #129   |
| urbandict-search  | @YueLiu-jina  |   | Merged  |  #119 |
|  x-as-service | @bwanglzu   | @YueLiu-jina  | Merged  | #122  |
| zh/news-search  | @YueLiu-jina  |   | Problem  | #143  |
| zh/webqa-search  |  @YueLiu-jina |   | Merged  | #124  |

**Comment by JoanFM** [comment]
We have to keep in mind to update the hub images to work with 0.4.1 as well

**Comment by bwanglzu** [comment]
Hi @lusloher , since I don't have the jira access at the moment, if you wanna keep track the migration progress, please follow this channel.

**Comment by JoanFM** [comment]
HelloWorld is merged now right?

**Comment by YueLiu-jina** [comment]
Yes, news is the only one left

**Comment by YueLiu-jina** [comment]
All examples except news-search have been migrated. News-search meets some problems that are non-trivial to solve with version 0.4.1. So maybe we will directly migrate it to 0.5 in another PR.
