### ISSUE TITLE
Rebuild docker images for broken examples and excutors

### ISSUE THREAD

**Issue by YueLiu-jina** [jina-ai/examples#123]
Now that lots of docker images are broken, this issue is aiming to checkout the validity of all exsiting dockerfile of example/executor, and re-build&&push docker images

**Comment by JoanFM** [comment]
@YueLiu-jina is this issue solved? or what is missing, let's put some `TODO-list` which check-boxes in the `description` so that we can track the evolution of these issues

**Comment by YueLiu-jina** [comment]
Now that lots of docker images are broken, this issue is aiming to checkout the validity of all exsiting dockerfile of example/executor, and re-build&&push docker images

**Comment by JoanFM** [comment]
> Now that lots of docker images are broken, this issue is aiming to checkout the validity of all exsiting dockerfile of example/executor, and re-build&&push docker images

Let's put this in the description
