### ISSUE TITLE
[flower-search] Unable to build docker container

### ISSUE THREAD

**Issue by madhukar01** [jina-ai/examples#135]
Trying to build the docker container to run the example - flower-search
Container build command -` docker build .`
Below is the complete log
This might be related to #123 

> Sending build context to Docker daemon  8.799MB
Step 1/10 : FROM pytorch/pytorch:latest
 ---> 6a2d656bcf94
Step 2/10 : WORKDIR /
 ---> Using cache
 ---> 73a3e9902629
Step 3/10 : ENV ENCODER yaml/encode.yml
 ---> Using cache
 ---> b988bad264e8
Step 4/10 : ENV TMP_WORKSPACE /workspace
 ---> Using cache
 ---> 223b73ad929c
Step 5/10 : RUN apt-get update &&     apt-get install --no-install-recommends -y curl
 ---> Using cache
 ---> bce477aa9731
Step 6/10 : RUN python -m pip install --no-cache-dir --upgrade pip &&     pip install --no-cache-dir click                                jina[http]==0.4.1                                jina[devel]==0.4.1                                pillow
 ---> Running in c6009ef99968
Collecting pip
  Downloading pip-20.2.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.2.1
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting jina[http]==0.4.1
  Downloading jina-0.4.1.tar.gz (181 kB)
Requirement already satisfied: pillow in /opt/conda/lib/python3.7/site-packages (7.2.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from jina[http]==0.4.1) (1.18.5)
Collecting pyzmq>=17.1.0
  Downloading pyzmq-19.0.2-cp37-cp37m-manylinux1_x86_64.whl (1.1 MB)
Collecting protobuf
  Downloading protobuf-3.12.4-cp37-cp37m-manylinux1_x86_64.whl (1.3 MB)
Collecting grpcio
  Downloading grpcio-1.30.0-cp37-cp37m-manylinux2010_x86_64.whl (3.0 MB)
Collecting ruamel.yaml>=0.15.89
  Downloading ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
Collecting tornado>=5.1.0
  Downloading tornado-6.0.4.tar.gz (496 kB)
Collecting gevent
  Downloading gevent-20.6.2-cp37-cp37m-manylinux2010_x86_64.whl (5.4 MB)
Collecting flask_cors
  Downloading Flask_Cors-3.0.8-py2.py3-none-any.whl (14 kB)
Collecting flask
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting python-magic
  Downloading python_magic-0.4.18-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: six>=1.9 in /opt/conda/lib/python3.7/site-packages (from protobuf->jina[http]==0.4.1) (1.14.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from protobuf->jina[http]==0.4.1) (46.4.0.post20200518)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9"
  Downloading ruamel.yaml.clib-0.2.0-cp37-cp37m-manylinux1_x86_64.whl (547 kB)
Collecting zope.interface
  Downloading zope.interface-5.1.0-cp37-cp37m-manylinux2010_x86_64.whl (235 kB)
Collecting greenlet>=0.4.16; platform_python_implementation == "CPython"
  Downloading greenlet-0.4.16-cp37-cp37m-manylinux1_x86_64.whl (45 kB)
Collecting zope.event
  Downloading zope.event-4.4-py2.py3-none-any.whl (7.6 kB)
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Requirement already satisfied: Jinja2>=2.10.1 in /opt/conda/lib/python3.7/site-packages (from flask->jina[http]==0.4.1) (2.11.2)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask->jina[http]==0.4.1) (1.1.1)
Building wheels for collected packages: jina, tornado
  Building wheel for jina (setup.py): started
  Building wheel for jina (setup.py): finished with status 'done'
  Created wheel for jina: filename=jina-0.4.1-py3-none-any.whl size=247647 sha256=edcd60663fc08d51fff5e20ee14763f14931e3fc7d88746194ce86235a6062f7
  Stored in directory: /tmp/pip-ephem-wheel-cache-h668sgde/wheels/07/a5/e6/e79c848b4803e55c2351ee51b5cc02e9e3566b66e4b2fd014d
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-6.0.4-cp37-cp37m-linux_x86_64.whl size=415150 sha256=e10c4b376640e9f85d4efaa12a8394b11739b54e1636a18b4c3ab1e344227834
  Stored in directory: /tmp/pip-ephem-wheel-cache-h668sgde/wheels/7d/14/fa/d88fb5da77d813ea0ffca38a2ab2a052874e9e1142bad0b348
Successfully built jina tornado
Installing collected packages: click, pyzmq, protobuf, grpcio, ruamel.yaml.clib, ruamel.yaml, tornado, zope.interface, greenlet, zope.event, gevent, itsdangerous, Werkzeug, flask, flask-cors, python-magic, jina
  Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel-yaml 0.15.87
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
The command '/bin/sh -c python -m pip install --no-cache-dir --upgrade pip &&     pip install --no-cache-dir click                                jina[http]==0.4.1                                jina[devel]==0.4.1                                pillow' returned a non-zero code: 1

**Comment by madhukar01** [comment]
On further debugging, This issue is being caused by upgrading pip - line 11 in Dockerfile

**Comment by madhukar01** [comment]
Removing the pip upgrade issues above error but leads to a new error while indexing (still part of building docker image)

> chunk_indexer@39[I]:setting up sockets...
  chunk_indexer@39[I]:input tcp://0.0.0.0:46275 (DEALER_CONNECT) 	 output tcp://0.0.0.0:48017 (PUSH_CONNECT)	 control over tcp://0.0.0.0:59131 (PAIR_BIND)
           JINA@39[E]:Since v0.3.6 jina uses uvloop to manage events and sockets, it often yields 20% speedupyou did not install uvloop. Try "pip install uvloop"
  chunk_indexer@39[S]:ready and listening
  chunk_indexer@30[I]:received "control" from chunk_indexer▸⚐
    doc_indexer@42[C]:unknown exception: AttributeError("'NoneType' object has no attribute 'logger'")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/jina/drivers/convert.py", line 60, in __init__
    import magic
  File "/opt/conda/lib/python3.7/site-packages/magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by madhukar01** [comment]
Seems like libmagic is missing in the base image
`apt-get install libmagic-dev` solves the above issue

**Comment by madhukar01** [comment]
My final Dockerfile is below. 

> FROM pytorch/pytorch:latest
> 
> WORKDIR /
> 
> ENV ENCODER yaml/encode.yml
> ENV TMP_WORKSPACE /workspace
> 
> RUN apt-get update && \
>     apt-get install --no-install-recommends -y curl libmagic-dev
> 
> RUN python -m pip install --no-cache-dir click \
>                                jina[http]==0.4.1 \
>                                jina[devel]==0.4.1 \
>                                pillow
> 
> RUN python -c "import torchvision.models as models; models.mobilenet_v2(pretrained=True)"
> 
> COPY . /
> 
> RUN bash get_data.sh && \
>     python app.py -t index -n 1000 && \
>     rm -rf /tmp/jina/flower
> 
> CMD ["python", "app.py","-t","query"]

**Comment by YueLiu-jina** [comment]
The problem did exist. Thank you for your wonderful Pull Request!
