### ISSUE TITLE
Search request in urbandict-search example gives no results | jina 0.4.11

### ISSUE THREAD

**Issue by ArturTan** [jina-ai/examples#165]
It seems that this [tutorial](https://github.com/jina-ai/examples/tree/master/urbandict-search) is not compatible with the current API. 

After running the following commands:
```
python3.7 prepare_data.py
python3.7 app.py -t index -n 100
python3.7 app.py -t query
```

And trying many queries like:
"dollar","undesirable; less-than optimum", "to vomit", etc. - all from the first 100 lines, no query is given.

Please find enclosed log file:

[error.log](https://github.com/jina-ai/examples/files/5114804/error.log)

**Comment by YueLiu-jina** [comment]
Hi @ArturTan , our current code is base in jina version 0.4.1. Please follow our tutorial and make sure to run `pip install --upgrade -r requirements.txt` before running other codes.
