### ISSUE TITLE
Empty search results when following my-first-jina-app tutorial

### ISSUE THREAD

**Issue by denysthegitmenace** [jina-ai/examples#168]
I indexed the startrek dataset and started the search server following the [my-first-jina-app](https://github.com/jina-ai/examples/tree/master/my-first-jina-app) tutorial.

Now, when I try to query my local endpoint through jinabox it just keeps hanging.
Alternatively, when I query it with curl I get the below output
```
➜  my_neural_search_project curl --request POST -d '{"top_k": 10, "mode": "search", "data": ["text:picard to riker"]}' -H 'Content-Type: application/json' 'http://0.0.0.0:65481/api/search'

{
  "requestId": 1,
  "search": {
    "docs": [
      {
        "id": 1,
        "weight": 1.0,
        "mimeType": "text/plain",
        "text": "text:picard to riker"
      }
    ]
  },
  "status": {}
}% 
```
The search server does not through any exceptions/errors.

Any ideas what I might be doing wrong?

**Comment by denysthegitmenace** [comment]
I noticed that the `workspace` folder is empty (so I would assume the index did not get created). Could that be a hint to the solution?

**Comment by alexcg1** [comment]
Hi there,

Apologies for these issues. Unfortunately cookiecutter-jina no longer works with Jina's latest code, so we've made the difficult decision to retire this tutorial until we have a more effective way for new users to bootstrap a simple Jina project.

When I wrote the tutorial (when Jina 0.3.0 was the latest release) it worked perfectly. Alas with the breaking changes of 0.4.0 that's no longer the case. In short, indexing failed silently (i.e. with no error messages), so the query command had nothing to actually query.

Please let me know if you have any other questions or feedback!
