### ISSUE TITLE
mac直接执行 python3 app.py -t index 出错

### ISSUE THREAD

**Issue by sssdjj** [jina-ai/examples#19]
objc[3871]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[3871]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by sssdjj** [comment]
不是在docker中

**Comment by hanxiao** [comment]
Please refer to https://docs.jina.ai/chapters/troubleshooting.html#objc-15934-nsplaceholderdictionary-initialize-may-have-been-in-progress-in-another-thread-when-fork-was-called

**Comment by nan-wang** [comment]
This error is due to the limit of threads in OS X. Please find more details in the docs.


```

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

```
