### ISSUE TITLE
southpark-example can't be developed on Windows 10

### ISSUE THREAD

**Issue by Zenahr** [jina-ai/examples#246]
Please add a note early on stating that the [Southpark Demo App](https://github.com/jina-ai/examples/tree/master/southpark-search) cannot be followed-along when working on a Windows machine.

**Comment by Zenahr** [comment]
related to #106

**Comment by JoanFM** [comment]
Hello @Zenahr ,

Thank you for raising this error,

Currently we do not support `Windows` but we have it in mind and we intend to support it.

**Comment by Zenahr** [comment]
@JoanFM I was just suggesting to add exactly this info at the top of the instructions so that people on Windows machines don't blindly try to follow them and then wonder why it's not working for them. I didn't ask for Windows compatability itself.

**Comment by JoanFM** [comment]
> @JoanFM I was just suggesting to add exactly this info at the top of the instructions so that people on Windows machines don't blindly try to follow them and then wonder why it's not working for them. I didn't ask for Windows compatability itself.

Really good point!! Sorry for the missunderstanding, you are right!

**Comment by alexcg1** [comment]
Hey @Zenahr - thanks for your feedback. Yeah, I think that would be a great idea and our team will get right on implementing that.

@pswu11 here's your chance to get stuck in with git and markdown!

**Comment by JoanFM** [comment]
@alexcg1 can we close this issue? Is the documentation properly added?

**Comment by Zenahr** [comment]
@JoanFM no it has not been added as of now.

![image](https://user-images.githubusercontent.com/47085752/104766607-29d6eb00-576b-11eb-8c01-544f6fe84a46.png)

I'd suggest some text like the following to be added to where the badly drawn arrow is pointing:

> Attention: This example can only be compiled on Linux machines. If you are a Windows user, do not try this out.

Or add the disclaimer to the `Prerequirements` section.
https://github.com/jina-ai/examples/tree/master/southpark-search#prerequirements

**Comment by JoanFM** [comment]
@alexcg1 could you check if this documentation is required or if the documentarion we have on that is considered enough?

**Comment by alexcg1** [comment]
@pswu11 could you add a one-line note at the top of the [root examples README](https://github.com/jina-ai/examples/blob/master/README.md) explaining that if you want Jina to work on Windows 10 you need to [follow the instructions](https://docs.jina.ai/chapters/install/os/on-wsl.html)

That way we cover **all** examples. Doing it piecemeal isn't very maintainable

**Comment by JoanFM** [comment]
I think it is solved by #356
