### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by myaxxxxx** [jina-ai/examples#29]
hello， when I run a demo of jina, i got some questions

As you can see, when I ran one of jina's demos called "x-as-service," the following error occurred

![image](https://user-images.githubusercontent.com/31684700/80910012-625ea200-8d5f-11ea-9fec-8a58e4c84eca.png)

I wonder if this is just my network problem or something else

thanks

**Comment by policeme** [comment]
[timeout_ready](https://github.com/jina-ai/examples/blob/57e37c7a4428f18a03747169d18dce113c21c51f/x-as-service/app.py#L27) 30s or even more, because the model initial time is very long.

**Comment by hanxiao** [comment]
when you start the app without having the image locally, it will pull the image first. Apparently, in your case this can not be finished in 20s. 

Try pull the image in advance, before start `python app.py`
```bash
docker pull jinaai/hub.executors.encoders.nlp.transformers-pytorch
```

**Comment by myaxxxxx** [comment]
> when you start the app without having the image locally, it will pull the image first. Apparently, in your case this can not be finished in 20s.
> 
> Try pull the image in advance before starting `python app.py`
> 
> ```shell
> docker pull jinaai/hub.executors.encoders.nlp.transformers-pytorch
> ```

thank s

**Comment by myaxxxxx** [comment]
I'm  so sorry I have another problem.
it shows "list index out of range"

![image](https://user-images.githubusercontent.com/31684700/80910661-a5227900-8d63-11ea-9bda-f1412b65dff7.png)

thanks

**Comment by hanxiao** [comment]
ok this is because the last update on compression feature in `jina-ai/jina` breaks the old hub image. I will trigger `jina-hub` rebuild.

**Comment by myaxxxxx** [comment]
Thank you very much

**Comment by hanxiao** [comment]
build is done according to https://hubstatus.jina.ai

please docker pull again and retry the app

**Comment by myaxxxxx** [comment]
it works, thank you
