### ISSUE TITLE
fail to start <class 'jina.peapods.container.ContainerPea'> with name encode-1

### ISSUE THREAD

**Issue by JamesGu14** [jina-ai/examples#30]
Hi team, when I execute the X-as-Service example from [here](https://github.com/jina-ai/examples/blob/master/x-as-service/app.py), service could not start. Could you help?

Full log as below:

<img width="1080" alt="Screen Shot 2020-05-07 at 10 35 16 AM" src="https://user-images.githubusercontent.com/3223774/81248253-84ea0700-904e-11ea-88b8-12bd5f78f498.png">

**Comment by hanxiao** [comment]
The image is broken due to the recent updates and the transformer is still based on the old base image.

I've triggered the rebuild of the image and please wait until the image is updated and try again

**Comment by hanxiao** [comment]
btw, make sure you install jina with docker via `pip install "jina[docker]"`

**Comment by JamesGu14** [comment]
well, when I try to pip install with extra, it warns "jina 0.1.8 does not provide the extra 'devel'", or "jina 0.1.8 does not provide the extra 'docker'", could it be the issue?

**Comment by hanxiao** [comment]
could you copy paste the log output of `pip install "jina[docker]"`? and what is your `pip -V`?

**Comment by JamesGu14** [comment]
![Screenshot from 2020-05-11 17-14-33](https://user-images.githubusercontent.com/3223774/81545059-ee4d7b00-93aa-11ea-909d-bb68f1e97df3.png)

I tried a few times with different versions of pip(19.1.x & 20.1.x) and jina(0.1.8 & 0.1.10), all tells that `WARNING: jina 0.1.10 does not provide the extra 'docker'`

**Comment by hanxiao** [comment]
@policeme can you confirm this issue on a new virtual environment?

**Comment by policeme** [comment]
@JamesGu14 which os is your os? this os of your pictures seem like deepin.

**Comment by policeme** [comment]
@hanxiao in ubuntu, I used this command `pip install "jina[docker]"` to install jina. the log same as above.

**Comment by hanxiao** [comment]
> @hanxiao in ubuntu, I used this command `pip install "jina[docker]"` to install jina. the log same as above.

so work or doesn't work?

**Comment by hanxiao** [comment]
@JamesGu14 try `pip install -U jina[devel]`

**Comment by hanxiao** [comment]
this should be solved in `0.1.11`, close
