### ISSUE TITLE
Use pathlib for paths

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/examples#300]
**Problem**
Since we are using a lot of `os.path` for directory/filepath operations, we can move to cleaner `pathlib` operations.

**Suggestion**
Replace all path related operations in core modules and test with pathlib's path

**Comment by nan-wang** [comment]
That's a good practice for integrating new Python features. 

## Reference
[https://realpython.com/python-pathlib/](https://realpython.com/python-pathlib/)

**Comment by carlosb1** [comment]
I am not sure if it is correct, but I see some examples out of date... I could try to update a few of them (with help if it is possible) and  include these new "features". Please, contradict me if I am wrong, I don't want to be rude.

**Comment by JoanFM** [comment]
Hey @carlosb1, no need to implement this since is not the default library in core to handle paths. Closing this issue
