### ISSUE TITLE
Error in customized example

### ISSUE THREAD

**Issue by carlosb1** [jina-ai/examples#324]
I am trying to set up an example (I could add it as a PR). I use as  reference `news_search`  and `southpark-search`  . It seems  all the flows and the  pipeline is built corretly, and I can append all the data.., But when I search I receive this error:
```
 BadDocType("fail to construct a document from b'\\x93\\x0e>\\xc7\\x8f\\r?\\xde-\\xdc>\\t\\xbc\\t\\xbe\\x84\\x1a\\x1f=a\\x8b\\xca;\\x86\\xc2\\x00=\\xe7u\\x06\\xbd9h\\xd4<\\xc50\\xe9=@!\\x8c\\xbe\\x80,6\\xbdx\\xcbi\\xbd\\xda|\\xbe\\xbd\\xd3\\xab#>Ewu\\xbd`\\xe5&=\\xe6{\\xe3\\xbe\\xf8z\\x00>]\\xc4\\xa4>?\\x17\\x9d=\\xc5\\x07^\\xbdT\\xa68\\xbc7\\xc5\\x11>\\xe7\\x96\\xdd\\xbd \\xe4\\xff\\xbc\\x1c\\xdf\\xf9<\\xa6\\xc0G>\\xb7\\xa0\\xba=\\x1f\\x9bQ:\\x91\\xde\\xac>]\\xfd?>\\x7f'")
```

My crafter class is something like this:

```
class TextExtractor(BaseCrafter):
    def craft(self, text: str, *args, **kwargs) -> Dict:
        values = text.split('[SEP]')
        return dict(weight=1., text=values[0].encode('utf8'), meta_info=values[1].encode('utf8'))
```
My data for this first step, it keep bing the `bcc news dataset`, I attach this database before  and after to parse the csv 
[info.tar.gz](https://github.com/jina-ai/examples/files/5750560/info.tar.gz)

The script `prepare_data.py` to parse information is used from the news-search [example](https://github.com/jina-ai/examples/blob/master/news_search/prepare_data.py) 

**UPDATE**: I am saving.  this example in one of my [repos](https://github.com/carlosb1/examples-python/tree/master/my-jina-example) before have running it.

**Comment by JoanFM** [comment]
> I am trying to set up an example (I could add it as a PR). I use as reference `news_search` and `southpark-search` . It seems all the flows and the pipeline is built corretly, and I can append all the data.., But when I search I receive this error:
> 
> ```
>  BadDocType("fail to construct a document from b'\\x93\\x0e>\\xc7\\x8f\\r?\\xde-\\xdc>\\t\\xbc\\t\\xbe\\x84\\x1a\\x1f=a\\x8b\\xca;\\x86\\xc2\\x00=\\xe7u\\x06\\xbd9h\\xd4<\\xc50\\xe9=@!\\x8c\\xbe\\x80,6\\xbdx\\xcbi\\xbd\\xda|\\xbe\\xbd\\xd3\\xab#>Ewu\\xbd`\\xe5&=\\xe6{\\xe3\\xbe\\xf8z\\x00>]\\xc4\\xa4>?\\x17\\x9d=\\xc5\\x07^\\xbdT\\xa68\\xbc7\\xc5\\x11>\\xe7\\x96\\xdd\\xbd \\xe4\\xff\\xbc\\x1c\\xdf\\xf9<\\xa6\\xc0G>\\xb7\\xa0\\xba=\\x1f\\x9bQ:\\x91\\xde\\xac>]\\xfd?>\\x7f'")
> ```
> 
> My crafter class is something like this:
> 
> ```
> class TextExtractor(BaseCrafter):
>     def craft(self, text: str, *args, **kwargs) -> Dict:
>         values = text.split('[SEP]')
>         return dict(weight=1., text=values[0].encode('utf8'), meta_info=values[1].encode('utf8'))
> ```
> 
> My data for this first step, it keep bing the `bcc news dataset`, I attach this database before and after to parse the csv
> [info.tar.gz](https://github.com/jina-ai/examples/files/5750560/info.tar.gz)
> 
> The script `prepare_data.py` to parse information is used from the news-search [example](https://github.com/jina-ai/examples/blob/master/news_search/prepare_data.py)

Hey @carlosb1 , can you provide a repo link to your example? So that we can better see where the potential problem exists? 

Thanks

**Comment by carlosb1** [comment]
https://github.com/carlosb1/examples-python/tree/master/my-jina-example <- I am saving in this repo.

**Comment by JoanFM** [comment]
Hey @carlosb1,

I have tried to reproduce the issue and I do not see the problem. Can u put some more context of the stacktrace?

I also see that you are reusing `TextExtractor` which I am not sure it is useful for your dataset.

**Comment by carlosb1** [comment]
I attached the logs. I don't know if it is normal. if I search "teenagers", it breaks but for "teenager" it doesn't find anything.
[index.log](https://github.com/jina-ai/examples/files/5751230/index.log)
[search.log](https://github.com/jina-ai/examples/files/5751231/search.log)

**Comment by JoanFM** [comment]
I can't reproduce right now, 

But I can say that the `Flow` for search looks a little weird. Please be aware that `news_search` is not up-to-date.

For instance, at Query and Index Flow u are using `Sentencizer` to break documents into chunks. Are you sure you want to segment your query?

**Comment by carlosb1** [comment]
I see... I got the instructions from the southpark-example but they are not used in the code... I admit, I only want to use a NLP example to play with news, fake news, etc... and send you a PR. It is possible I overcomplicated the problem and with another example and a the cookiecutter template would be a better straight solution.

**Comment by florian-hoenicke** [comment]
@carlosb1 I checked out your repo and ran your app.py. It is not producing the exception when I enter your search terms.
Could you give me a detailed instruction on how I can reproduce the BadDocType error?

**Comment by carlosb1** [comment]
Well, I found the error, I didn t clean my folder with the embedded ones. I suppose it was getting old information, my next point would be to understand why I don t query and found anything...

**Comment by JoanFM** [comment]
I think your flows and pods are not correct. First we need to know what usecase you are trying to build.

1. What is your input?
2. Do you want to encode your input directly or you want to chunk it and encode the chunks?
3. Is your query supposed to be chunk or should it be used directly for search?

**Comment by carlosb1** [comment]
Yes, for this reason, it can be better to simplify my problem with a simpler example.
1.- Sentences as a first prototype, sentences and tags for a second iteration
2.- I suppose for large texts, it could be necessary to chunk. To start, we can simplify without this. 
3-  I think, it is not necessary chunk....

**Comment by JoanFM** [comment]
> Yes, for this reason, it can be better to simplify my problem with a simpler example.
> 1.- Sentences as a first prototype, sentences and tags for a second iteration
> 2.- I suppose for large texts, it could be necessary to chunk. To start, we can simplify without this.
> 3- I think, it is not necessary chunk....

then your first example can be based on southpark example but without the extraction pod

**Comment by carlosb1** [comment]
I did a first [iteration](https://github.com/jina-ai/examples/pull/332), It is basic but I did as far as I could

**Comment by carlosb1** [comment]
I added a new example.. I admit I am not sure if it provides enough features to be merged:

 
Furthemore, a not related test break the PR.
```
chunk_matches = sorted(chunk_matches, key=lambda x: x['score']['value'], reverse=False)
tests/test_multireslyrics.py:99: 
```

**Comment by JoanFM** [comment]
The tests have been fixed, soon we will do some refactoring in the examples

**Comment by JoanFM** [comment]
Hey @carlosb1 ,

I see that you opened a PR with a new example (although we may ask to be moved into the personal repo), but does this `issue` remain valid?

**Comment by carlosb1** [comment]
It check it. It shouldn't be new one.  I close it.
