### ISSUE TITLE
Query function is not working for urbandict-search example

### ISSUE THREAD

**Issue by kazanture** [jina-ai/examples#34]
I am having the below problem while trying to run query for urbandict-search (python app.py -t query
).

`TypeError: py_client() got multiple values for keyword argument 'port_grpc'
`

The cause is in _get_client function of flow; port_grpc is already defined but it is also coming from kwargs from above.
The reason is flow-query.yml of urbandict-search has "port_grpc: 56798" defined in it. This line should be removed.

**Comment by nan-wang** [comment]
> I am having the below problem while trying to run query for urbandict-search (python app.py -t query
> ).
> 
> `TypeError: py_client() got multiple values for keyword argument 'port_grpc' `
> 
> The cause is in _get_client function of flow; port_grpc is already defined but it is also coming from kwargs from above.
> The reason is flow-query.yml of urbandict-search has "port_grpc: 56798" defined in it. This line should be removed.

hi, @kazanture Thanks for posting! Would you please post the version information of jina so that we can dig into this issue?
```shell
jina --version
```

**Comment by kazanture** [comment]
`(examples) emre@emre-desktop:~/examples/urbandict-search$ jina --version
0.1.12
`

**Comment by kazanture** [comment]
But i believe it is not about the jina version; it is about the flow-query.yml of this specific example. All the other examples do not have "port_grpc: 56798" line in flow-query.yml . Which is triggering the bug.
But maybe you prefer to fix it in jina so even if the port is provided in the yaml file; it doesnt fail.

**Comment by nan-wang** [comment]
hi, @kazanture This bug is due to the conflicts between two changes on both `examples` and `jina` sides. Yes, you are right about the quick fix. Furthermore, I've raised an issue at [jina::issue-416](https://github.com/jina-ai/jina/issues/416 ) and working on a more general fix.
- [jina::PR-390](https://github.com/jina-ai/jina/pull/390)
- [examples::PR-32](https://github.com/jina-ai/examples/pull/32)

**Comment by nan-wang** [comment]
@kazanture hi, there. I've fix this issue at [PR-418](https://github.com/jina-ai/jina/pull/418). Would you please give it another shot? ;)
