### ISSUE TITLE
Broken link for advanced vector search

### ISSUE THREAD

**Issue by tadej-redstone** [jina-ai/examples#340]
In this table in [this](https://github.com/jina-ai/examples#%EF%B8%8F--advanced-examples) section. Also, in the TOC in Advanced vector search, a couple of links are broken (sections renamed or don't exist anymore)

**Comment by nan-wang** [comment]
Thanks for your feedback! ❤️  

Oh btw, we have a slack channel for warm-heart contributors like you, where we discuss code, PR, and future of Jina. Strongly recommend to join us

- If you haven't joined our Slack, [click here to join](https://join.slack.com/t/jina-ai/shared_invite/zt-dkl7x8p0-rVCv~3Fdc3~Dpwx7T7XG8w)
- 👨‍💻 👩‍💻 ➡️  https://jina-ai.slack.com/messages/contributors/
