### ISSUE TITLE
Docker sdk for python not included

### ISSUE THREAD

**Issue by samjoy** [jina-ai/examples#342]
In the advanced vector search example, if you are using annoy or faiss, you are really using their respective docker images. Thus you have to install the docker sdk for python ([https://pypi.org/project/docker/](https://pypi.org/project/docker/)). The docker sdk is not installed as it is not present in the requirements.txt. Please add docker to the requirements.txt.

**Comment by JoanFM** [comment]
> In the advanced vector search example, if you are using annoy or faiss, you are really using their respective docker images. Thus you have to install the docker sdk for python (https://pypi.org/project/docker/). The docker sdk is not installed as it is not present in the requirements.txt. Please add docker to the requirements.txt.

Hey @samjoy thanks for the issue, would u like to open a PR to add it yourself?

**Comment by samjoy** [comment]
sure will do it soon
