### ISSUE TITLE
Meta data

### ISSUE THREAD

**Issue by annaakhil** [jina-ai/examples#373]
**Describe the bug**
when I am querying the documents I am able to retrieve related documents but the metadata related to that document is not getting displayed?? The character names are the metadata in this document.

**Screenshots**
![image](https://user-images.githubusercontent.com/49350396/105956680-2c580f80-609e-11eb-85f0-11dfc02fc09a.png)
![image](https://user-images.githubusercontent.com/49350396/105956750-442f9380-609e-11eb-875f-33779beae284.png)
![image](https://user-images.githubusercontent.com/49350396/105957040-abe5de80-609e-11eb-987c-b1ac518bd9ea.png)
![image](https://user-images.githubusercontent.com/49350396/105957117-c28c3580-609e-11eb-97c2-d53d267c6316.png)

**Comment by annaakhil** [comment]
@cristianmtr Thank you for the info. I have one more small issue, when I am implementing the South park search example I am getting an issue while searching the document on _merge_matches
![image](https://user-images.githubusercontent.com/49350396/105982671-99c76880-60bd-11eb-90d1-ef347eecfc36.png)
![image](https://user-images.githubusercontent.com/49350396/105982767-bf547200-60bd-11eb-85a2-b497e785a47b.png)

**Comment by cristianmtr** [comment]
I just tried running this and it works for me.

Can you send your config here?

Please paste logs and config as code snippets, like

```yaml
!something
...
```

**Comment by annaakhil** [comment]
jina                          0.8.2
jina-proto                    0.0.76
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.4
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.32.0
ruamel.yaml                   0.16.12
python                        3.8.5
platform                      Linux
platform-release              4.19.128-microsoft-standard
platform-version              #1 SMP Tue Jun 23 12:58:10 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /home/akhil/.local/lib/python3.8/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)

**Comment by cristianmtr** [comment]
Why are you using that older version?

The south park example is built on 

```
jina                          0.9.14
jina-proto                    0.0.77
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.5
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.35.0
pyyaml                        5.4.1
python                        3.8.5
platform                      Linux
platform-release              5.8.0-40-generic
platform-version              #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021
architecture                  x86_64
processor                     x86_64
jina-resources                /home/cristian/envs/southpark/lib/python3.8/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_ID                   (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_RAISE_ERROR_EARLY        (unset)
JINA_RANDOM_PORTS             (unset)
JINA_RANDOM_PORT_MAX          (unset)
JINA_RANDOM_PORT_MIN          (unset)
JINA_SOCKET_HWM               (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)
```

**Comment by annaakhil** [comment]
oh sorry, my bad thanks @cristianmtr, and for Southpark-incremental-indexing example jina version is 0.9.14 or any higher version?

**Comment by cristianmtr** [comment]
Like I said, south park incremental search is deprecated for now. Thus why it was moved to `to_move`. 

It should still work if you use those specific requirements.

We are going to either 1) upgrade that to `1.0`, or 2) add incremental indexing to another example

Meanwhile you can try adapting the incremental indexing from our tests/integration to your needs
