### ISSUE TITLE
star_trek % pip install -r requirements.txt

### ISSUE THREAD

**Issue by conanchen** [jina-ai/examples#386]
follow this page: https://github.com/jina-ai/examples/tree/master/my-first-jina-app#troubleshooting
got :
Collecting websockets
  Using cached websockets-8.1.tar.gz (58 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.0 (from jina[devel,tensorflow,torch])
ERROR: No matching distribution found for tensorflow>=2.0

**Comment by Yongxuanzhang** [comment]
Hi @conanchen! Thanks for using Jina!
The first-jina-app example is outdated and going to be replaced by https://github.com/jina-ai/examples/tree/master/wikipedia-sentences. 
You may want to check other examples as well. 
Thanks!

**Comment by hargup** [comment]
@Yongxuanzhang Thanks for the comment. It will be nice, you can put a deprecation notice in the README about this app.

**Comment by Yongxuanzhang** [comment]
> @Yongxuanzhang Thanks for the comment. It will be nice if you can put a deprecation notice in the README about this app.

Sure! It will be done after we remove all outdated examples. Thanks for your comment!
