### ISSUE TITLE
examples/southpark-search: encoder driver throws an exception, the sequel pipeline may not work properly

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/examples#41]
# Environment

* Fresh install of Ubuntu 20.04
* `/usr/bin/python` points to `/usr/bin/python3`

# Reproduce

**Note:** Already installed all prerequisite packages via `pip`, and downloaded data via `get_data.sh`

```
python app.py -t index -n 10000
```

# Result

See attached [error.log](https://github.com/jina-ai/examples/files/4625909/error.log)

# Notes

I encountered the exact (I think) same error on my Manjaro install, so it's likely not an Ubuntu thing

**Comment by nan-wang** [comment]
hi, there. What's the output message of `which python`?

**Comment by nan-wang** [comment]
hi, @alexcg1 This is fixed in the latest `jina`. Would you please pull the codes and give it another try?

**Comment by alexcg1** [comment]
Not at my PC right now but pretty sure it's /usr/bin/python or /usr/bin/python3

Also it's a "real" install, not virtualbox or docker or anything like that. 8gb of memory. 10gb free disk space at least. Quad-core CPU which isn't being overtaxed by Jina hello-world (which runs perfectly through the docker image)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alexcg1** [comment]
I'll check tomorrow. Thanks!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nan-wang** [comment]
In the log, the exception stated that

```
  File "/home/alexcg/.local/lib/python3.8/site-packages/jina/executors/encoders/nlp/transformer.py", line 69, in encode
    output = self.tensor2array(extra_output[0])
IndexError: list index out of range
```

And this is fixed in [PR-412](https://github.com/jina-ai/jina/pull/412).

**Comment by alexcg1** [comment]
Good to hear! However, is the `jina` python package updated? I'm trying to upgrade it via `pip install` but only seeing version 0.1.11 which I already have installed.

Otherwise it seems testing the examples just comes up with same errors if I can't upgrade jina itself

**Comment by alexcg1** [comment]
Quick update:

* For some reason pip wouldn't upgrade jina without me specifically telling it `pip install jina==0.1.12` - so I thought it hadn't been pushed to pipy (even after uninstalling via pip and reinstalling, it kept trying to get 0.1.11

I'm now getting status messages about chunk indexer and things aren't choking so soon yet. So it looks like this bug is fixed! Woohoo!
