### ISSUE TITLE
Adding example of cross modal search

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#410]
Update example of cross modal search, our objective is:  

- [x] Clean up current cross-modal search example 
- [x] Add evaluation to the cross modal search example, to evaluate search performance
- [x] Integrate CLIP model into cross modal search with evaluation
- [x] Compare the current implementation (VSE++ model) with CLIP model to see the performance gain
- [x] Some leftovers, such as Readme. Dockerfile.
- [ ]  Write blog @davidbp

**Comment by bwanglzu** [comment]
For evaluation:
Image to text  -> use BLEUEvaluator to measure the difference between generated text and labeled sentences.
text to image -> use precision/recall/f1 and MRR to measure the ranking result

**Comment by JoanFM** [comment]
Hey @bwanglzu , I would just use precision/recall for both, at the end we know the expected groundtruth. Does that make sense?

**Comment by bwanglzu** [comment]
make sense to me!

**Comment by bwanglzu** [comment]
evaluation mode: 
`text2image`: Query image by text and compute mRR. CLIP 0.4710, VSE++ 0.4527, 8000 images CLIP takes 13 minutes, VSE++ 32 minutes.
`image2text`: PLACEHOLDER

**Comment by bwanglzu** [comment]
```bash
MeanReciprocalRank is: 0.36691655362180126
python evaluate.py -e text2image -i 16000 -n 4000 -m vse -s 32

MeanReciprocalRank is: 0.4018869057074189
python evaluate.py -e text2image -i 16000 -n 4000 -m clip -s 32

MeanReciprocalRank is: 0.40887093350663783
python evaluate.py -e image2text -i 16000 -n 4000 -m clip -s 32

MeanReciprocalRank is: 0.37910317568853497
python evaluate.py -e image2text -i 16000 -n 4000 -m vse -s 32
```
