### ISSUE TITLE
MM pdf search example 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#424]
### Example creation ticket
To showcase the real functionality of Jina, we should build a PDF search solution that can jointly search image & text as in mm-helloworld. 

The requirement as a "basic" PDF search that leverages Jina: 
jointly image and text (please find some PDFs have both image & text, easy, you can download 10 arxiv paper, they all have images and figures)
segment the doc using sections/chapaters/paragrahs

The result should be published on the example repo. With sufficient test and documentation.

**Comment by bwanglzu** [comment]
cc @Kelton8Z
