### ISSUE TITLE
object search doesn't work in python 3.8

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/examples#425]
**error message**
Message: 'RuntimeError(\'No such operator torchvision::nms\')\n add "--quiet-error" to suppress the exception details'
Same as https://github.com/pytorch/vision/issues/1916

**Version**
Python 3.8.5

aiofiles==0.6.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
fastapi==0.63.0
fluent-logger==0.10.0
future==0.18.2
gevent==21.1.2
greenlet==1.0.0
grpcio==1.36.1
h11==0.12.0
idna==2.10
jina==1.0.5
lz4==3.1.1
msgpack==1.0.2
numpy==1.20.1
Pillow==8.1.0
protobuf==3.15.6
pydantic==1.8.1
python-magic==0.4.22
python-multipart==0.0.5
PyYAML==5.4.1
pyzmq==22.0.3
requests==2.25.1
six==1.15.0
starlette==0.13.6
torch==1.6.0
torchvision==0.7.0
tornado==6.1
typing-extensions==3.7.4.3
urllib3==1.26.3
uvicorn==0.13.4
uvloop==0.15.2
websockets==8.1
wsproto==1.0.0
zope.event==4.5.0
zope.interface==5.2.0

**Comment by FionnD** [comment]
Hi @Yongxuanzhang 

To better understand this, can you provide the steps you used that lead to the problem?

**Comment by nan-wang** [comment]
This should have been fixed in #598 and corresponding tests for `3.8` have been added.
