### ISSUE TITLE
wikipedia-sentences-incremental: repository does not exist

### ISSUE THREAD

**Issue by franquil** [jina-ai/examples#440]
Following [the guide](https://github.com/jina-ai/examples/blob/master/wikipedia-sentences-incremental/README.md) at wikipedia-sentences-incremental directory, an error:
 `Unable to find image 'jinahub/app.example.wikipedia-sentences-incremental:0.1-0.9.24' locally
docker: Error response from daemon: pull access denied for jinahub/app.example.wikipedia-sentences-incremental, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
`
will be occurred, when run `docker run -p 45678:45678 jinahub/app.example.wikipedia-sentences-incremental:0.1-0.9.24` command.

Looks like the required repository does not exist.

**Comment by rutujasurve94** [comment]
Hey @franquil  could you try with `jinahub/app.example.wikipedia-sentences-30k:0.2.10-1.0.10` instead? This link is valid https://hub.docker.com/r/jinahub/app.example.wikipedia-sentences-30k.
You can navigate the available images for examples with prefix this prefix: `https://hub.docker.com/r/jinahub/app.example`

**Comment by franquil** [comment]
Hi @rutujasurve94 , thanks again. I build an image called `jinahub/app.example.wikipedia-sentences-incremental:0.1-1.0.13` and published to jina hub. Here's the pop up [page](https://api.jina.ai/hub/?jh=jinahub%2Fapp.example.wikipedia-sentences-incremental%3A0.1-1.0.13) at the end. I suppose the command `docker run -p 45678:45678 jinahub/app.example.wikipedia-sentences-incremental:0.1-1.0.13` should be working now. (the version should be modified to `1.0.13` rather than `0.9.24` at README)

By the way, I found a typo at the last sh command (`curl --request POST -d '{"top_k": 10, "mode": "search",  "data": ["text:hello world"]}' -H 'Content-Type: application/json' 'http://0.0.0.0:45678/api/search'``), the last character ` should be removed, otherwise it won't work.

Because I found the results will take a while to show up in the example comparing with the `wikipedia sentences`, another potential improvement would be reducing the default `top_k` parameter to 2 (or 3). So that, users would get a fast response rather than waiting for a while and don't know what happened. 

What would you think?

**Comment by rutujasurve94** [comment]
Hi @franquil thanks for the insights on this and glad to know that you could successfully publish the image.
I'll make the correction for the `curl` query :
```curl --request POST -d '{"top_k": 10, "mode": "search", "data": ["text:hello world"]}' -H 'Content-Type: application/json' 'http://0.0.0.0:45678/api/search'```
We can tweak the `top_k` param to return few most relevant results for the incremental case for sure

**Comment by franquil** [comment]
Hi @rutujasurve94 thanks for your reply. In terms of the built image(`jinahub/app.example.wikipedia-sentences-incremental:0.1-1.0.13`), I can found it on Docker Hub, is it available on [dashboard-hub](https://dashboard.jina.ai/#/hub/explore)? If it is, how can I find it?

Thanks for your clarification about the query issue.

**Comment by rutujasurve94** [comment]
Hi @franquil, dashboard-hub has the pod images (all types of executors hosted), wikipedia examples is a type of `app` (example)

**Comment by franquil** [comment]
Thanks, @rutujasurve94 . I searched with the "example" and the "demo"  filters on dashboard-hub page, however, still couldn't find the image I posted. It may be out of this issue's cope, and I suppose the issue can be closed now.

**Comment by alexcg1** [comment]
I guess this can be closed now @franquil @FionnD @rutujasurve94 ?

**Comment by franquil** [comment]
@alexcg1 Seems that the [doc](https://github.com/jina-ai/examples/tree/master/wikipedia-sentences-incremental) is not updated especially the last part "Run in Docker". Furthermore, looks like there's a new update two weeks ago, which corresponding docker image doesn't exist, when I try to rebuild it, an error below occurred:
```
@ 6[C]:inputs is not valid! FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/jina/clients/request/__init__.py", line 56, in request_generator
    for batch in batch_iterator(data, request_size):
  File "/opt/conda/lib/python3.8/site-packages/jina/helper.py", line 229, in batch_iterator
    chunk = tuple(islice(data, batch_size))
  File "/opt/conda/lib/python3.8/site-packages/jina/clients/sugary_io.py", line 63, in _input_lines
    with open(filepath, read_mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/input-1.txt'
```
To fix the issue, I suppose the docker image should be rebuilt and upload to remote hub, and the README file should be updated.
