### ISSUE TITLE
wikipedia-sentence-search: broken anchor links at README.md

### ISSUE THREAD

**Issue by franquil** [jina-ai/examples#441]
Two anchor links (*push to Jina Hub* and *Search section*) at *Build a Docker Image* section are broken.

**Comment by rutujasurve94** [comment]
Hi, the links are working (they point to the README of the `wikipedia` example. For pushing the image to Jina Hub,
follow: `docker build -f Dockerfile -t {DOCKER_IMAGE_TAG} . `
Do `jina login` to authenticate & authorize yourself and trigger the push to `jinahub`

**Comment by franquil** [comment]
Hi @rutujasurve94 , thanks for your comment. They do point to the READEME page, however, the anchor `#push-to-jina-hub` and `#search` being used do not exist in that page.

A simple fix would be adding an anchor (`<a name="push-to-jina-hub"></a>`) around the "Push to Jina Hub" title and another anchor (<a name="search"></a>`) around the "Search" title at README. So that, users wouldn't get confused when clicking those anchors at "Build a Docker Image" section.

Sorry, if it's not clear.

**Comment by FionnD** [comment]
I think @franquil means these two sections are dead [links](https://imgur.com/a/UIdYwmM )

@rutujasurve94 do you agree?

**Comment by rutujasurve94** [comment]
@franquil @FionnD yes, this sounds good, I'll fix these links up

**Comment by alexcg1** [comment]
Did this get fixed @rutujasurve94 ?

**Comment by rutujasurve94** [comment]
Fix in https://github.com/jina-ai/examples/pull/496

**Comment by rutujasurve94** [comment]
This is solved now
