### ISSUE TITLE
add teaching comments to examples' YAML files

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/examples#442]
From https://jina-ai.slack.com/archives/C0169V26ATY/p1616457075043300

**Comment by cristianmtr** [comment]
Can we reference the PR here? Did we add to all of them?

**Comment by FionnD** [comment]
I had already opened a new ticket https://github.com/jina-ai/examples/issues/445 which was tracking them without seeing yours, which is my fault. I was closing this to prevent duplication
