### ISSUE TITLE
pokedex-with-bit: dead anchor links and typo at README

### ISSUE THREAD

**Issue by franquil** [jina-ai/examples#443]
The README at pokedex-with-bit is basically good. Found a couple of small issues:

- Some of the anchor links at Table of Contents section are not working; (for example, 'Run outside of Docker' and 'Run in Docker' etc.)
- The port string '345678' should be replaced with '45678' at the example command `curl --verbose --request POST -d '{"top_k": 10, "mode": "search",  "data": ["data:image/png;base64...}' -H 'Content-Type: application/json' 'http://0.0.0.0:34567/api/search'`

**Comment by FionnD** [comment]
@jina-ai/dev-rel could one of you guys take this issue please?

**Comment by Yongxuanzhang** [comment]
Can I take this one? Should be a quick fix. @FionnD

**Comment by FionnD** [comment]
Yes please do @Yongxuanzhang  :)

**Comment by alexcg1** [comment]
In future let's let @rutujasurve94 handle these. As engineer co-ordinator she's responsible for example maintenance
