### ISSUE TITLE
object-search: conflict error and broken links etc.

### ISSUE THREAD

**Issue by franquil** [jina-ai/examples#444]
A couple of issues found at object-search example:

- The "read the Jina installation guide for details" link at README will direct users to a 404 page; Fixed in PR https://github.com/jina-ai/examples/pull/511
- The "Jina YAML syntax for executor, driver and flow" at "Documentation" section of README will direct users to a 404 page; (Looks like this Document section is copied from a template, other examples' README which includes the link are also broken) Fixed in https://github.com/jina-ai/examples/pull/511
- There's no docker instructions being used at README, so the sentence `To save you from dependency hell, we'll use the containerized version in these instructions. That means you only need to have Docker installed. No Python virtualenv, no Python package (un)install.` is not appropriate and could be removed (or add Docker instructions to show the example?);
fixed in https://github.com/jina-ai/examples/pull/511
- Lack of information about the `kaggle` CLI being used in the example, would it be better to add a bit of extra information about it? Or add a requirement section at README to introduce all needed dependencies? Fixed in https://github.com/jina-ai/examples/pull/511
-  'data/f8k/images' directory doesn't exist by default, before running `mv Images data/f8k/images` command which introduced at README, the directory should be created (for example by running `mkdir -p data/f8k/images`); also fixed in https://github.com/jina-ai/examples/pull/511
- A conflict occurred when running `pip install -r requirements.txt`:
```
ERROR: Cannot install -r requirements.txt (line 3) and torch==1.7.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.7.1
    torchvision 0.7.0 depends on torch==1.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```
The conflict could be fixed by updating torchvision from '0.7.0' to '0.8.2' at "requirements.txt";

**Comment by FionnD** [comment]
@rutujasurve94 could you also take this issue and implement the suggestions where possible?

**Comment by rutujasurve94** [comment]
hi @FionnD @franquil we are specifying the upgraded versions of the dependencies in the `requirements` file for the object-search example to be compatible with the latest jina version soon.

**Comment by FionnD** [comment]
Thanks for the update @rutujasurve94! What's the status on the other points @franquil mentions?

**Comment by FionnD** [comment]
Hi @franquil 

Sorry for the delay in getting back to you. @aga11313 is fixing the README of this example which covers all your points. If you have time, you'd be more then welcome to leave a review on that PR https://github.com/jina-ai/examples/pull/511 :) 

Otherwise, thank you for raising these issues and sorry for the delay in getting them done!
