### ISSUE TITLE
Update examples to REST CRUD interface

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#447]
### Maintenance
All our examples should be using the REST CRUD interface and not the /api/{mode}which is deprecated. 

**Acceptance Criteria**
This ticket is done when: All 13 examples on the example repo are working correctly and using the REST CRUD interface. 

[Updated by Fionn Friday 30th April] 

- [ ] advanced-vector-search
- [ ] audio-search 
- [ ] chinese-text-search 
- [ ] cross-modal-search 
- [x] fashion-example-query
- [x] multimodal-search-pdf 
- [ ] multimodal-search-tirg 
- [ ] multires-lyrics-search 
- [x] object-search 
- [ ] pokedex-with-bit 
- [ ] tumblr-gif-search 
- [x] wikipedia-sentences #453   (Done)
- [x] wikipedia-sentences-incremental #452  (Done)

**Comment by cristianmtr** [comment]
The checklist for each of these would be:

- update Jina to 1.1.0 (if not already at that version or higher)
- modify flow yamls to enable REST API
- add `index_rest` method that indexes docs using the /index REST API
- add `index_rest` as CLI option to `-t` (via click options)
- change README to point towards `/search` (NOT `/api/search`)

See https://github.com/jina-ai/examples/pull/453 and https://github.com/jina-ai/examples/pull/452

**Comment by nan-wang** [comment]
> The checklist for each of these would be:
> 
> * update Jina to 1.1.0 (if not already at that version or higher)
> * modify flow yamls to enable REST API
> * add `index_rest` method that indexes docs using the /index REST API
> * add `index_rest` as CLI option to `-t` (via click options)
> * change README to point towards `/search` (NOT `/api/search`)
> 
> See #453 and #452

Good point. @rutujasurve94 Let's start to update the examples.

**Comment by rutujasurve94** [comment]
I'm beginning work on this today onwards

**Comment by cristianmtr** [comment]
@rutujasurve94 make sure to add the PRs to this issue's parent comment and check it off

**Comment by alexcg1** [comment]
I'm happy to take on pokedex since I'm looking at doing some work on it anyway

**Comment by rutujasurve94** [comment]
https://github.com/jina-ai/examples/pull/465 closes Advanced Vector Search

**Comment by rutujasurve94** [comment]
https://github.com/jina-ai/examples/pull/466 closes Cross Modal Search

**Comment by rutujasurve94** [comment]
https://github.com/jina-ai/examples/pull/470 solves Multires Lyrics

**Comment by rutujasurve94** [comment]
https://github.com/jina-ai/examples/pull/471 solves Object Search

**Comment by rutujasurve94** [comment]
https://github.com/jina-ai/examples/pull/473 solves Pokedex with Bit

**Comment by rutujasurve94** [comment]
https://github.com/jina-ai/examples/pull/469 solves Fashion Example

**Comment by nan-wang** [comment]
@cristianmtr @FionnD I suggest we hold on progressing this ticket because it will introduce quite a lot of duplicated codes in all the examples. Basically, this will require that all the examples load the files, wrap them up to an HTTP request and send to different APIs. This will make the examples even harder to maintain. I see the motivation is to show how to use RESTful API to do CRUD in jina, but I suggest to show this in one example instead of copy-paste to every example.

**Comment by FionnD** [comment]
Hi @nan-wang 

Make sense, let's close this issue so?
