### ISSUE TITLE
Add notice as to which version of Jina examples work with. 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#448]
**Feature request:**
A notice should be added to the top of all the READMEs in the example repo specifying which version of Jina these examples work with. The following text snippet is a good suggestion for what to add. 

⚠️ Please note that examples currently only work with Jina version 1.1. Please make sure you are running this version when using the examples. `pip install jina == 1.1`

**Comment by rutujasurve94** [comment]
Working on `wikipedia`, `cross modal`, `multi modal`, `object search tumblr` examples to update the latest version compatibility.
