### ISSUE TITLE
wikipedia-sentences: Error during indexing

### ISSUE THREAD

**Issue by shahrukhx01** [jina-ai/examples#456]
I'm trying to run the `wikipedia-sentences` example but I get an error when I run the `python app.py -t index` on OSX. 
The environment details are following:
OS: OSX Big Sur V11.2
Python: Python 3.9.2

I'm getting the following logs on my terminal:

`
 encoder@43439[I]:starting jina.peapods.runtimes.zmq.zed.ZEDRuntime...
        encoder@43439[I]:input tcp://0.0.0.0:54492 (PULL_BIND) output tcp://0.0.0.0:54503 (PUSH_CONNECT) control over tcp://0.0.0.0:54490 (PAIR_BIND)
        indexer@43440[I]:starting jina.peapods.runtimes.zmq.zed.ZEDRuntime...
        indexer@43440[I]:input tcp://0.0.0.0:54503 (PULL_BIND) output tcp://0.0.0.0:54504 (PUSH_BIND) control over tcp://0.0.0.0:54502 (PAIR_BIND)
        gateway@43441[I]:starting jina.peapods.runtimes.asyncio.grpc.GRPCRuntime...
        gateway@43441[I]:input tcp://0.0.0.0:54504 (PULL_CONNECT) output tcp://0.0.0.0:54492 (PUSH_CONNECT) control over ipc:///var/folders/s4/4l6cbdrn7cq2m4vs14xz9qpm0000gn/T/tmpga_xzqut (PAIR_BIND)
        gateway@43441[S]:GRPCRuntime is listening at: 0.0.0.0:54512
TransformerTorchEncoder@43439[W]:"auto" pooling_strategy is deprecated, Defaulting to  "cls" to maintain the old default behavior.
TransformerTorchEncoder@43439[I]:post_init may take some time...
   NumpyIndexer@43440[I]:post_init may take some time...
   NumpyIndexer@43440[I]:post_init may take some time takes 0 seconds (0.00s)
   NumpyIndexer@43440[S]:successfully built NumpyIndexer from a yaml config
BinaryPbIndexer@43440[I]:post_init may take some time...
BinaryPbIndexer@43440[I]:post_init may take some time takes 0 seconds (0.00s)
BinaryPbIndexer@43440[S]:successfully built BinaryPbIndexer from a yaml config
CompoundIndexer@43440[I]:post_init may take some time...
CompoundIndexer@43440[I]:post_init may take some time takes 0 seconds (0.00s)
CompoundIndexer@43440[S]:successfully built CompoundIndexer from a yaml config
CompoundIndexer@43440[W]:Setting workspace of vecidx to workspace/indexer
CompoundIndexer@43440[W]:Setting workspace of docidx to workspace/indexer
objc[43439]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[43439]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

`

**Comment by JoanFM** [comment]
Hey @shahrukhx01 ,

This problem seems to be related to some specific MacOS configuration, disabling multithreaded and multiprocessing forks.

See if this thread may be helpful:

https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr

**Comment by shahrukhx01** [comment]
@JoanFM  Thank you for your prompt response, I already did set the `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=yes`, in `.bash_profile`, however, missed exporting the env variable, re-looking at it made me realize that. Cheers!
