### ISSUE TITLE
add QPS timing scripts to each example

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/examples#457]
Follow steps defined in https://github.com/jina-ai/examples/pull/449

- add `TimeContext` to index and query ops:

```python
            with TimeContext(f'QPS: indexing {len(list(data_func_list))}', logger=flow.logger):
```

and

```python
            with TimeContext(f'QPS: query with {len(query_input)}', logger=flow.logger):
```

- add `setup_run.sh` script to example directory that prepares and runs the example, while piping the output into a `metrics.txt` file

ex.:

```bash
#!/bin/bash
# these scripts will contain everything that needs to be run before the example
# downloading data, model, preprocessing etc.
bash ./get_data.sh siftsmall && \
rm -rf workspace && \
bash ./generate_training_data.sh && \
python app.py -t index | tee metrics.txt && \
python app.py -t query | tee >> metrics.txt
```

Create a PR and edit this comment to add next to the example

- [x] advanced-vector-search https://github.com/jina-ai/examples/pull/449
- [x] audio-search https://github.com/jina-ai/examples/pull/449
- [x] chinese-text-search https://github.com/jina-ai/examples/pull/459
- [x] cross-modal-search https://github.com/jina-ai/examples/pull/459
- [x] fashion-example-query https://github.com/jina-ai/examples/pull/459
- [x] multimodal-search-pdf
- [x] multimodal-search-tirg https://github.com/jina-ai/examples/pull/459
- [x] multires-lyrics-search https://github.com/jina-ai/examples/pull/459
- [ ] ner-search
- [x] object-search https://github.com/jina-ai/examples/pull/477
- [x] pokedex-with-bit https://github.com/jina-ai/examples/pull/460
- [ ] southpark-search
- [x] tumblr-gif-search https://github.com/jina-ai/examples/pull/460
- [x] wikipedia-sentences https://github.com/jina-ai/examples/pull/460
- [x] wikipedia-sentences-incremental https://github.com/jina-ai/examples/pull/460

**Comment by slettner** [comment]
@cristianmtr The `ner-search` and `southpark-search` examples are not present anymore, correct?
If yes, I think this issue is done.

**Comment by cristianmtr** [comment]
> @cristianmtr The `ner-search` and `southpark-search` examples are not present anymore, correct?
> If yes, I think this issue is done.

Yes, those were remnants of previous branches in my local repo. This is done! Good job, everyone :100:
