### ISSUE TITLE
Fix executor signature

### ISSUE THREAD

**Issue by slettner** [jina-ai/examples#478]
Changes in the Jina API introduced breaking changes in the signature of executors. 

Where previously 
```
class MyEncoder(BaseEncoder):  
    def encode(self, data: 'np.ndarray', *args, **kwargs):
```
was working the new API does not support the `data` arg anymore. 
It needs to be changed to `content`, otherwise an attribute error will be thrown.

```
        encoder@2242[E]:AttributeError("{'data'} is now deprecated and not a valid argument of the executor function, please change `data` to `content: 'np.ndarray'` in your executor function. details: https://github.com/jina-ai/jina/pull/2313/")
```

The following tests need to be fixed:
- [x] advanced-vector-search https://github.com/jina-ai/examples/pull/479
- [x] fashion-example-query https://github.com/jina-ai/examples/pull/479
- [x] audio-search https://github.com/jina-ai/examples/pull/479

**Comment by FionnD** [comment]
Hey @slettner if all three PR are merged is this ticket done? :)

**Comment by slettner** [comment]
Yes, the changes for this issue are covered by PRs referenced by this ticket https://github.com/jina-ai/examples/issues/447
