### ISSUE TITLE
Pokedex: Dashboard not working

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/examples#482]
In Pokedex example it states you can monitor indexing using Jina Dashboard. However opening https://dashboard.jina.ai it says 'could not connect to Jina instance'. I guess Pokedex doesn't have Dashboard port enabled?

## Fixes

- Remove this reference from the readme

**Comment by aga11313** [comment]
@alexcg1 is this about the part where it says you can view the logs?

**Comment by alexcg1** [comment]
@aga11313 this bit: https://github.com/jina-ai/examples/tree/master/pokedex-with-bit#monitor-progress
