### ISSUE TITLE
Southpark-search indexing process got stuck

### ISSUE THREAD

**Issue by pswu11** [jina-ai/examples#49]
I have been trying to run southpark-search following the instruction and the process seemed to stuck somewhere every time. (Before I have already tried `jina hello-world` and it can be executed without a problem.)

At first I thought it's still in progress just very slowly. But then I checked the system monitor they all seem kinda "idle". Nothing changed even after 20+ minutes. 

## Environment

Desktop: Fedora 31 (kernel 5.6)
Python version: 3.7.7
Jina version: 0.1.10 (installed via PyPi)

## Steps

- Cloned the project to my local folder
- `pip install -r requirements.txt` **> Success**
- `bash ./get_data.sh` **> Success**
- `python app.py -t index -n 10000` **> Process Stuck**

## Logs
Below is the logs that I reproduced today:
https://gist.github.com/pswu11/0724531689b5f700a40ccd4384c3fb15

## Screenshot
![Screenshot from 2020-05-14 12-06-47](https://user-images.githubusercontent.com/48913707/81922103-ec1e3300-95db-11ea-8917-9ac4d64ee9eb.png)

**Comment by nan-wang** [comment]
@pswu11 hi, there. This bug is fixed at [PR-422](https://github.com/jina-ai/jina/pull/422). Would you please pull the latest codes and give it another try?

**Comment by pswu11** [comment]
> @pswu11 hi, there. This bug is fixed at [PR-422](https://github.com/jina-ai/jina/pull/422). Would you please pull the latest codes and give it another try?

Hello Nan, thank you!
I have tried to run southpark-search with the latest version of Jina (0.1.12). The indexing seemed to be running all the way very fine until this point (1205 batch), and the process stopped again. 
Do you think it's the same bug?

```
index [=                   ] 📃   9608 ⏱️ 1479.8s 🐎 6.5/s   1201 batch        encoder@8760[I]:received "index" from gateway▸splittor-0▸⚐
  chunk_indexer@8763[I]:received "index" from gateway▸splittor-0▸encoder-0▸⚐
       join_all@8769[I]:received "index" from gateway▸splittor-0▸encoder-0▸chunk_indexer-0▸⚐
       join_all@8769[I]:collected 2/2 parts of IndexRequest
index [==                  ] 📃   9616 ⏱️ 1480.9s 🐎 6.5/s   1202 batch        encoder@8760[I]:received "index" from gateway▸splittor-0▸⚐
  chunk_indexer@8763[I]:received "index" from gateway▸splittor-0▸encoder-0▸⚐
       join_all@8769[I]:received "index" from gateway▸splittor-0▸encoder-0▸chunk_indexer-0▸⚐
       join_all@8769[I]:collected 2/2 parts of IndexRequest
index [===                 ] 📃   9624 ⏱️ 1482.1s 🐎 6.5/s   1203 batch        encoder@8760[I]:received "index" from gateway▸splittor-0▸⚐
  chunk_indexer@8763[I]:received "index" from gateway▸splittor-0▸encoder-0▸⚐
       join_all@8769[I]:received "index" from gateway▸splittor-0▸encoder-0▸chunk_indexer-0▸⚐
       join_all@8769[I]:collected 2/2 parts of IndexRequest
index [====                ] 📃   9632 ⏱️ 1483.2s 🐎 6.5/s   1204 batch  chunk_indexer@8763[I]:received "index" from gateway▸splittor-0▸encoder-0▸⚐
       join_all@8769[I]:received "index" from gateway▸splittor-0▸encoder-0▸chunk_indexer-0▸⚐
       join_all@8769[I]:collected 2/2 parts of IndexRequest
index [=====               ] 📃   9640 ⏱️ 1484.5s 🐎 6.5/s   1205 batch 
```
