### ISSUE TITLE
Updating example READMEs

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#518]
Each Readme should follow the template in https://github.com/jina-ai/examples/pull/497 
The code in the example should be run and correctly run. 

- [x] Semantic Wikipedia Search https://github.com/jina-ai/examples/pull/515 
- [x] Add incremental Indexing https://github.com/jina-ai/examples/pull/577
- [x] Search lyrics https://github.com/jina-ai/examples/pull/535 
- [x] Google Big Transfer with Pokemon #626
- [x] Object detection  https://github.com/jina-ai/examples/pull/511
- [ ] Youtube audio search 
- [ ] Tumblr GIF [**To be deleted by Han**]
- [ ] Index & query with FAISS
- [x] Cross Modal https://github.com/jina-ai/examples/pull/614
- [ ] Multi-modal 
- [ ] PDF search 
- [x] Query Lang https://github.com/jina-ai/examples/pull/483

**Comment by FionnD** [comment]
This issue is now being tracked in https://github.com/jina-ai/internal-tasks/issues/83

**Comment by jakob1111996** [comment]
Can we close this issue because only archived examples are missing?

**Comment by jakob1111996** [comment]
@CatStark @nan-wang

**Comment by CatStark** [comment]
Yes, I'll close this
