### ISSUE TITLE
OBJECT SEARCH: bug report: inputs is not valid! BadRequestType('error when building IndexRequestProto from

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#519]
Running: 
* OS.X 11.1 (M1 chip) 
* jina==1.1.0

While running the **object detection search**, I hit the following error. 
```
index |█                   | 📃      0 ⏱️ 0.0s 🐎 0.0/s      0      batchindex ...	           JINA@7502[C]:inputs is not valid! BadRequestType('error when building IndexRequestProto from (b\'\\xff\\xd8\\xff\\xe0\\x00\\x10JFIF\\x00\\x01\\x01\\x01\\x00H\\x00H\\x00\\x00\\xff\\xdb\\x00C\\x00\\x01\\x01\\x01\\x01\\x01\\x01\\x01\\x01\\x01\\x01\\x01\\x01\\x01\\x02\\x02\\x03\\x02\\x02\\x02\\x02\\x02\\x04\\x03\\x03\\x02\\x03\\x05\\x04\\x05\\x05\\x05\\x04\\x0

``` 

Step to reproduce: 
1. Clone and download the repo. 
2. Run the requirement script 
3. Download the kaggle data
4. Run: `python app.py -task index -n 1000 -overwrite True`
5. Index fails, with the above error. 

Full error message can be found [here](https://gist.github.com/FionnD/39882ec294f9685d2775f89c571786ab).

**Comment by nan-wang** [comment]
I guess this is due to the fact that the `hub` module in your local environment is out of date. I've added `hub` requirements

**Comment by FionnD** [comment]
Thanks, @nan-wang , I pulled your branch but it's still not working. The same occurs.

**Comment by FionnD** [comment]
@cristianmtr PR #522 didn't fix that issue for me, did you try it?

**Comment by cristianmtr** [comment]
yes, it worked. But I see this was in reference to a specific PR, not to `master`

**Comment by FionnD** [comment]
If you get it working let me know, I can jump on a quick call with you in the next 20 minutes to see if it a local issue for me
