### ISSUE TITLE
Add s3 credentials to CI

### ISSUE THREAD

**Issue by slettner** [jina-ai/examples#536]
To successfully download data-sets from our S3 bucket within the CI runner (relevant for the performance measurement https://github.com/jina-ai/examples/issues/457) AWS credentials need to be provided via env variables. Specifically, we need 
- [ ] `AWS_ACCESS_KEY_ID`
- [ ] `AWS_SECRET_ACCESS_KEY`

to refer to the credential of an AWS user with read permissions to the S3 bucket.

**Comment by jacobowitz** [comment]
Test PR for examples repo can be found here: https://github.com/jina-ai/examples/pull/539
