### ISSUE TITLE
add an example for using tf serving

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/examples#54]
Based on the official tf serving tutorial at [https://www.tensorflow.org/tfx/serving/serving_basic](https://www.tensorflow.org/tfx/serving/serving_basic), we build an encoder for encoding `mnist` images.

Here is the plan,
- [ ] serve the mnist classification examples based on the tutorial at https://www.tensorflow.org/tfx/serving/serving_basic. One need to tweak the model export a little bit and use the second last layer for output instead of the classification results.
- [ ] implement `MnistTFServingClientEncoder` inherited from `BaseTFServingClientEncoder`. We've made a simple one in the unit test, https://github.com/jina-ai/jina/blob/master/tests/unit/executors/encoders/clients.py#L10.
- [ ] build an example that load the MNIST data set and encode with the `MnistTFServingClientEncoder`. One can refer to the `hello-world` example in the jina core, https://github.com/jina-ai/jina/blob/master/jina/helloworld/__init__.py
- [ ] write down a tutorial

**Comment by lazyprgmr** [comment]
I am looking to resolve this issue. Is this issue about serving jina using tf serving (as opposed to docker) or is it about building a representation of mnist that would be useful for jina.

**Comment by JoanFM** [comment]
Hello @lazyprgmr,

Sorry for the late reply, this issue should be about having an **encoder** that can use **tensorflow serving** , and show an example of it.
