### ISSUE TITLE
multimodal-pdf: data downloader crash: can't find 'data/Cross-model-with-clip.pdf'

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/examples#541]
Running `get_data.py` fails with error:

```
Traceback (most recent call last):
  File "get_data.py", line 22, in <module>
    with open(name, 'wb') as outputStream:
FileNotFoundError: [Errno 2] No such file or directory: 'data/Cross-model-with-clip.pdf'
```

## Proposed solution

Get rid of the script altogether and populate `data/` with some simple PDF examples (from our own blog to avoid copyright issues). This won't bulk up the repo too much and means less work for user and less maintenance for us

**Comment by Yongxuanzhang** [comment]
Actually, the script is downloading blogs from our website, and I also populate 3 pdf files in toy_data folder. 
How about directly removing the get_data.py?
