### ISSUE TITLE
multimodal-pdf: missing system dependencies

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/examples#542]
On clean AWS ec2, multimodal PDF search fails out of the box because of missing system libraries.

## Proposed solution

Update readme to tell users to install:

- libcairo2
- libpango-1.0-0
- libpangocairo-1.0-0

## Environment

`lsb_release -a` output:

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**Comment by nan-wang** [comment]
The CI passed with a fresh installation at (`Ubuntu 20.04.2 LTS`)[https://github.com/jina-ai/examples/runs/2582483071?check_suite_focus=true#step:1:4]. @alexcg1 Would you please give it another try to the latest codes?

**Comment by nan-wang** [comment]
I've update the tests and the codes at #593

**Comment by alexcg1** [comment]
I'm testing on AWS now, and getting strangeness: Indexing starts fine, memory and CPU spikes, then it just chills out using no CPU and just idling after indexing one doc. Then it spikes again for another doc and chills out. I'm now waiting for it to get back to work.
![Screenshot from 2021-05-17 12-39-54](https://user-images.githubusercontent.com/4182659/118475895-23528300-b70d-11eb-9f3b-4c74eac5235b.png)
![Screenshot from 2021-05-17 12-39-15](https://user-images.githubusercontent.com/4182659/118475903-23eb1980-b70d-11eb-8a17-6b206b1b25c9.png)
![Screenshot from 2021-05-17 12-37-52](https://user-images.githubusercontent.com/4182659/118475905-2483b000-b70d-11eb-8482-3d34540f4bae.png)

**Comment by FionnD** [comment]
So @alexcg1 still not working, @nan-wang any ideas?

**Comment by alexcg1** [comment]
It's a big :shrug: from me I'm afraid

**Comment by nan-wang** [comment]
May I get full logs from you and the `jina -vf` information? It is difficult to reproduce this issue from my side.

**Comment by nan-wang** [comment]
From the screenshots you provide, it seems that your program hangs up at the 2nd request. I guess it might related to the memory issues. Would you please try it on another instance with more memory or set `export JINA_PARALLEL=1`?

**Comment by FionnD** [comment]
@bwanglzu  has noticed some issues with the request size already, see [here](https://github.com/jina-ai/examples/issues/613#issuecomment-842940648).

**Comment by alexcg1** [comment]
- [`jina -vf`](https://github.com/jina-ai/examples/files/6521196/vf.txt)
- [log](https://github.com/jina-ai/examples/files/6521197/log2.txt)

@nan-wang I ran it on a fresh venv in a fresh clone just now. Same results

**Comment by alexcg1** [comment]
`python --version`: `Python 3.8.5`

Running on stock AWS ec2 with Ubuntu 20.04.1 LTS

**Comment by nan-wang** [comment]
> From the screenshots you provide, it seems that your program hangs up at the 2nd request. I guess it might related to the memory issues. Would you please try it on another instance with more memory or set `export JINA_PARALLEL=1`?

@alexcg1 Have you tried this? set `export JINA_PARALLEL=1`

**Comment by nan-wang** [comment]
I noticed that there was only 3.8GB memory in the instance. However, running `python app.py -t index` takes more than 6 GB memory. Setting `export JINA_PARALLEL=1` reduced the memory usage to 5GB.

**Comment by alexcg1** [comment]
Nice. After doing that `python app.py -t index` worked perfectly on ec2

**Comment by alexcg1** [comment]
And querying seems to work too
