### ISSUE TITLE
Issue with indexing the tumblr-gif examples

### ISSUE THREAD

**Issue by Shubhamsaboo** [jina-ai/examples#613]
while indexing the tumblr-gif example. It got stuck here and not progressing forward.

![image](https://user-images.githubusercontent.com/31396011/118464964-0d4dbe00-b71f-11eb-9be9-b35a6e267ab4.png)
 
OS: Linux
Python Version: 3.7

**Comment by bwanglzu** [comment]
@Shubhamsaboo looking into this :)

**Comment by bwanglzu** [comment]
hi @Shubhamsaboo , can you try the following things:
1. remove your workspace folder inside `tumblr-gif-search` folder with `rm -rf workspace`.
2. in `app.py` , line 39, change `request_size` to a smaller number, e.g. 8.
3. run the index flow again, with `python app.py -t index`

**Comment by bwanglzu** [comment]
if the above solution still not working for you, try to change line 18 to line 20 in `app.py`:

```python
SHARDS_DOC = 1
SHARDS_CHUNK_SEG = 1
SHARDS_INDEXER = 1 
```

To set the shards to 1, to reduce system resource usage

**Comment by bwanglzu** [comment]
I'm able to index successfully with the above settings:

![image](https://user-images.githubusercontent.com/9794489/118615058-a5e84a80-b7c0-11eb-9261-5a784bc90339.png)

**Comment by Shubhamsaboo** [comment]
It worked with the above settings!
