### ISSUE TITLE
refactor: upgrade examples to release 2.0

### ISSUE THREAD

**Issue by jakob1111996** [jina-ai/examples#621]
We want to know how examples will run with Jina 2.0.
The following tasks should be finished for each of them:
- Use Jina 2.0 interface
- C&P Executors from Hub and adopt to new Executor base class
- Adopt Readme according to the Example Template #518 
- Add comments to YAML files to make them better understandable #445 

Examples to be updated:
- [x] wikipedia-sentences #619 
- [x] pokedex #626
- [x] multi modal PDF #629 
- [x] multires-lyrics #648 **Sebastian, Jakob**
- [x] cross-model https://github.com/jina-ai/examples/pull/631 
- [ ] query-while-indexing (only once dump-load approach has been agreed upon) **Kelton**: https://github.com/jina-ai/examples/pull/665

Other tasks:
- [x] Move all other examples to legacy and update example README. 
- [x] Create tutorials

We might continue with more afterwards.

**Comment by alexcg1** [comment]
As discussed in meeting today, I'd recommend merging these uni-modal (mono-modal?) examples into pokedex, and possibly renaming the example to "image/audio/video search" or similar:

- audio search
- tumblr gif search

Also, if we can get a decent metadata-heavy text dataset with good chunkability and searchability, we could look at merging the text-based examples (wikipedia-*, multires-lyrics) in future

**Comment by alexcg1** [comment]
Might also be good to rename 'wikipedia-sentences' to plain old 'text-search'. Makes it more google-able, and if/when we change the dataset we can retain the old URL

**Comment by nan-wang** [comment]
I share the same view with @alexcg1, we need to rename it just `example-audio-search`, `example-video-search`, `example-text-search`. As we are moving to `2.0`, I suggest pushing the proposal we had before that we should split the examples into separated repos.

**Comment by alexcg1** [comment]
Who can handle that @nan-wang ? I might have some capacity today to get started

**Comment by alexcg1** [comment]
Do we have a list somewhere of

- what we're updating?
- what we're merging?
- what we're deleting?

If not, I'll create a table in this thread and we can discuss

@nan-wang

**Comment by alexcg1** [comment]
> I share the same view with @alexcg1, we need to rename it just `example-audio-search`, `example-video-search`, `example-text-search`. As we are moving to `2.0`, I suggest pushing the proposal we had before that we should split the examples into separated repos.

I suggest we wait until all other example work is finished before doing this. If we change names mid-stream people are going to have a nightmare properly merging

**Comment by slettner** [comment]
I will take on the multi-modal-pdf @nan-wang

**Comment by FionnD** [comment]
@alexcg1 @nan-wang @theUnkownName  updated the ticket with some tasks from the meeting

**Comment by jakob1111996** [comment]
@nan-wang @CatStark @florian-hoenicke Some of these examples have been upgraded on an older version of jina2.0. We should use hub executors in all examples and update all of them to the latest jina version. Do you agree?

**Comment by alexcg1** [comment]
I really like the idea of using Hub Executors - many folks learn Jina by adapting the examples, so if Hub is baked in then they'll keep using Hub stuff (except for when they *need* to build their own Executors, which they can then push to Hub :smile: )

**Comment by nan-wang** [comment]
> We should use hub executors in all examples and update all of them to the latest jina version. Do you agree?

Sure, let's do it.
