### ISSUE TITLE
dataset(chinese): use something more modern, less classical

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/examples#622]
### Option 1

Hongloumeng (the current dataset) is really old stuff. I'm not sure the bert-chinese model is well-equipped for handling classical (i.e. not modern) Chinese. It would be like asking bert-base-uncased to handle Shakespeare or Chaucer. Or Beowulf.

How about something more:
a) Contemporary (and better suited for the model)
b) Practical (meets a use case, like ecommerce, Q+A)

### Option 2 (my preference)

Ideally I think this should really be folded into a generic text search example based on our current wikipedia example (since all we change is model + dataset). So perhaps we should just merge this whole example? (Discussed with @slettner @maximilianwerk and @florian-hoenicke earlier today)

**Comment by Yongxuanzhang** [comment]
I agreed to merge it into Wikipedia example, actually, I have proposed this on slack long time ago. 😄

**Comment by alexcg1** [comment]
Yay, another example can bite the dust! :fire: :fire: :fire:

**Comment by Yongxuanzhang** [comment]
> @Yongxuanzhang are you going to work on this actively now or later?

Maybe later? I can wait until Wikipedia 2.0 is ready

**Comment by Kelton8Z** [comment]
We could perhaps incorporate [BAAI](https://www.baai.ac.cn/en)'s datasets and models in https://resource.wudaoai.cn/home

**Comment by alexcg1** [comment]
I don't think we're even updating this example any more @Kelton8Z

**Comment by alexcg1** [comment]
I'll close this issue for now
