### ISSUE TITLE
examples/southpark-search throws exception

### ISSUE THREAD

**Issue by fhaase2** [jina-ai/examples#64]
The southpark-search throws an exception in the query stage for me. Following error:
`unknown exception: 'NoneType' object has no attribute 'shape'`
in `jina/executors/indexers/vector/numpy.py",` line 148, in _ext_arrs`

I can also see this in the logs:
`you can not query from <jina.executors.indexers.vector.numpy.NumpyIndexer object at 0x7fb6f03d4250> as its "query_handler" is not set. If you are indexing data from scratch then it is fine. If you are querying data then the index file must be empty or broken.`

Can someone reproduce this?

**Comment by hanxiao** [comment]
could it be you double indexed the data? currently there is no support on the incremental indexing.

try clear the index data first, run index and run query

**Comment by fhaase2** [comment]
Yes, you are correct. Thanks for your hint.
