### ISSUE TITLE
Key Error in 'multimodal-search-pdf' example

### ISSUE THREAD

**Issue by omarfarooqs** [jina-ai/examples#661]
I am getting the following error when running trying to execute a query. 
`keyValueIndexer@25462[E]:KeyError('root_doc_id')`

Please help.

**Comment by ennioferreirab** [comment]
Waiting for help too. Same error

**Comment by Yongxuanzhang** [comment]
Hi, @omarfarooqs @ennioferreirab thank you so much for reporting this issue.
Could you try out this branch? https://github.com/jina-ai/examples/pull/662
