### ISSUE TITLE
Search Chinese docs.

### ISSUE THREAD

**Issue by xiaoxiongfeng** [jina-ai/examples#663]
I have 70,000,000docs, I want to search the most similar text. The language is Chinese. Is there a example?

**Comment by Yongxuanzhang** [comment]
Hi, yes.
You could check this example. `https://github.com/jina-ai/examples/tree/master/wikipedia-sentences` .
To apply it on Chineses dataset, we just need to change the encoder model trained on Chinese. E.g. bert-base-chinese
