### ISSUE TITLE
How can I get my index?

### ISSUE THREAD

**Issue by xiaoxiongfeng** [jina-ai/examples#667]
**Describe your proposal/problem**

I run this, but I dont know where is my index;Or How can I store it! What does `flow.index(docs)` do?
![image](https://user-images.githubusercontent.com/33524866/123961338-d0920980-d9e2-11eb-858d-1ddd5a7fc1a7.png)

https://github.com/jina-ai/examples/tree/master/wikipedia-sentences
---

**Environment**

**Screenshots**

**Comment by nan-wang** [comment]
> How can I store it

The index is stored by [`NumpyIndexer`](https://github.com/jina-ai/examples/blob/master/wikipedia-sentences/indexer.py#L6). In this demo, the index is only stored in the memory.
