### ISSUE TITLE
section links in READMEs' table of content not referenced properly 

### ISSUE THREAD

**Issue by Kelton8Z** [jina-ai/examples#668]

**Comment by CatStark** [comment]
I think it's the same as this ticket right? https://github.com/jina-ai/jina/issues/2872 @Kelton8Z

**Comment by Kelton8Z** [comment]
> I think it's the same as this ticket right? [jina-ai/jina#2872](https://github.com/jina-ai/jina/issues/2872) @Kelton8Z

not exactly, that issue regards README of the examples repo, this one I meant the READMEs of actual examples
