### ISSUE TITLE
AttributeError in Wikipedia Sentences Example

### ISSUE THREAD

**Issue by karndeb** [jina-ai/examples#674]
While testing the wikipedia sentences example, I am getting Attribute Error for score in the indexer.py file at line 29 which is `d.score.value = 1 - _dist` . 

The Traceback:-

![jina](https://user-images.githubusercontent.com/36044259/125249034-65193780-e312-11eb-931d-dc25cf0c22c8.PNG)

Jina version is 2.0.5

Please help

**Comment by Kelton8Z** [comment]
The example code is not updated to the latest document api, the right attribute now is `scores`, which is a key value pair.
e.g. you need to do `d.scores['cosine'] = 1 - _dist` as documented in https://github.com/jina-ai/jina/blob/master/.github/2.0/cookbooks/Document.md#add-relevancy-to-documents

**Comment by karndeb** [comment]
@Kelton8Z Thanks. Closing the issue
