### ISSUE TITLE
Refactoring code since context manager is not supported.

### ISSUE THREAD

**Issue by rudranshsharma123** [jina-ai/examples#700]
I believe lines 
This: https://github.com/jina-ai/examples/blob/6138e006cd4435bdebac77447e2c7dd914284681/cross-modal-search/dataset.py#L120
and this: https://github.com/jina-ai/examples/blob/6138e006cd4435bdebac77447e2c7dd914284681/cross-modal-search/dataset.py#L115
needs to be changed since Jina does not support context manager anymore. 
Because following the example yields this issue:
![image](https://user-images.githubusercontent.com/67827010/129455052-4c4877b2-c530-4f71-92c5-856c4a37fe30.png)
I believe that's the only thing that needs to be changed.

**Comment by rudranshsharma123** [comment]
I believe these two lines only need change. If I am correct I would like to be the one to close and make my contribution to this project!

**Comment by bwanglzu** [comment]
@rudranshsharma123 do it!

**Comment by rudranshsharma123** [comment]
I think it's fixed and I did the workflow correctly. Feel free to correct me if I am wrong (I am still new to all this)
