### ISSUE TITLE
wikipedia-sentences inaccurate readme

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/examples#705]
In this step, it says "Once indexing is completed, a search prompt will appear in your terminal". But it will not, the search prompt will only appear after you run another query flow: `python app.py -t query`

https://github.com/jina-ai/examples/tree/master/wikipedia-sentences#-step-4-query-your-indexed-data

**Comment by jakob1111996** [comment]
I agree, I seem to have overlooked this.
