### ISSUE TITLE
flower-search and urbandict-search examples not working

### ISSUE THREAD

**Issue by YueLiu-jina** [jina-ai/examples#72]
I met problems running flower-search and urbandict-search. Error messages are as follow:
![error message](https://user-images.githubusercontent.com/64522311/84762428-60922a80-affd-11ea-9e46-249b2e622d2d.png)
![error mess2](https://user-images.githubusercontent.com/64522311/84762432-625bee00-affd-11ea-9f10-6194d04827d7.png)

The problem seems related to the use of buffer. I haven't tested other buffer-used examples. But when I change all buffer back to raw_bytes, both can work well.

**Comment by hanxiao** [comment]
lack of context, no version info. can't reproduce
