### ISSUE TITLE
x-as-service: Fix automatic download of the transformer image

### ISSUE THREAD

**Issue by khituras** [jina-ai/examples#81]
The README states
` In the example above, we use a prebuilt image from Jina Hub. It automatically pulls the image to local when you run this flow.`

However, I just cloned the repository and ran `app.py` without success. I needed to pull the image manually. Then `app.py` run without issues.

Perhaps the problem is that the image to download is too large to be readily downloaded in 20s depending the connection (working from home here).

**Comment by alexcg1** [comment]
Hello again! Did you get any error messages when you ran `app.py`? If so, could you try running

```
python app.py <blah> &> log.txt
```

`&>` will send all stdout and stderr messages to a file (assuming you're using a bash or zsh, I don't know about other weird shells) which would really help us find out the issue.

Cheers!

**Comment by khituras** [comment]
Hi there! Sure. I just removed the image and got the issue again. I attach the output file resulting of the command `python app.py &> log.txt`.
[log.txt](https://github.com/jina-ai/examples/files/4836530/log.txt)

**Comment by alexcg1** [comment]
Can confirm. I just tried running `python app.py` (with no other args) and got similar result. My log attached too for the dev team's reference

Note: I didn't actually follow any other steps in the example. Most of the yaml files seem to already exist without having to do anything except type `python app.py <blah>`

[log.txt](https://github.com/jina-ai/examples/files/4836535/log.txt)

**Comment by nan-wang** [comment]
hi, there. This is due to the timeout_ready is not set properly, `timeout_ready` is set to 20000ms in `app.py`.

```
f = (Flow(callback_on_body=True)
     .add(name='spit', uses='Sentencizer')
     .add(name='encode', uses='jinaai/hub.executors.encoders.nlp.transformers-pytorch',
          parallel=2, timeout_ready=20000))
```

Another solution is to try to run the following to pull the image before running.
```
docker pull jinaai/hub.executors.encoders.nlp.transformers-pytorch
```

**Comment by JoanFM** [comment]
Closing as per lack of activity
